# Generated by Django 5.2 on 2025-07-20 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_category_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='auther',
            new_name='author',
        ),
    ]
