# Generated by Django 5.2 on 2025-08-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('imageUrl', models.CharField(max_length=1000)),
                ('content', models.CharField(max_length=4000)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
