# Generated by Django 5.2.5 on 2025-08-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0006_alter_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
