# Generated by Django 5.2.5 on 2025-08-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0007_alter_page_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="content",
            field=models.CharField(max_length=6000),
        ),
        migrations.AlterField(
            model_name="page",
            name="title",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.CharField(max_length=6000),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=300),
        ),
    ]
