# Generated by Django 5.2.6 on 2025-09-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0008_alter_page_content_alter_page_title_alter_post_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="post",
            name="excerpt",
            field=models.CharField(max_length=1000),
        ),
    ]
